# Generated by Django 6.0 on 2025-12-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('user_id', models.IntegerField()),
                ('title', models.CharField()),
                ('text', models.CharField()),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('push', 'Push'), ('telegram', 'Telegram')], default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending')),
                ('sent_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
