# Generated by Django 6.0 on 2025-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodel",
            name="uuid",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="notificationmodel",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["created_at"],
                name="idx_pending_created_at",
            ),
        ),
    ]
