"""
Django settings for notification_service project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from base64 import b64decode

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv(BASE_DIR.parent.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vf&wn5l#&9e+37f!zye%svch$j*on5qmg#*_be@1so3$pk%6r&'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'notification_service.adapters.api.apps.NotificationsConfig',
    'notification_service.adapters.db.apps.DbConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'notification_service.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notification_service.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


environment = os.environ.get('DJANGO_ENVIRONMENT', 'local')
if environment not in ["local", "production"]:
    raise EnvironmentError("Please define valid DJANGO_ENVIRONMENT.")

os.environ.setdefault(
    'DJANGO_SETTINGS_MODULE',
    f'notification_service.config.settings.{environment}'
)

# Celery
CELERY_BEAT_SCHEDULE = {
    "notification-send-check": {
        "task": (
            "notification_service.adapters.workers.celery.send_notifications"
        ),
        "schedule": 2.0,
    },
}

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", "localhost")
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT", "5672")
RABBITMQ_USER = os.getenv("RABBITMQ_USER", "guest")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD", "guest")
RABBITMQ_VHOST = os.getenv("RABBITMQ_VHOST", "/")

CELERY_BROKER_URL = (
    f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}"
    f"@{RABBITMQ_HOST}:{RABBITMQ_PORT}{RABBITMQ_VHOST}"
)


# JWT
JWT_AUTH_ENABLED = os.getenv("JWT_AUTH_ENABLED", "False") != "False"
JWT_AUDIENCE = os.getenv("JWT_AUDIENCE", "notification-service")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "RS256")
JWT_PUBLIC_KEY = b64decode(os.getenv("JWT_PUBLIC_KEY", "")).decode("utf8")

# Email notification settings
EMAIL_NOTIFICATIONS_ENABLED = os.getenv("EMAIL_NOTIFICATIONS_ENABLED", "True") != "False"
EMAIL_NOTIFICATIONS_SMTP_SERVER = os.getenv("EMAIL_NOTIFICATIONS_SMTP_SERVER", "localhost")
EMAIL_NOTIFICATIONS_SMTP_PORT = int(os.getenv("EMAIL_NOTIFICATIONS_SMTP_PORT", "587"))
EMAIL_NOTIFICATIONS_SMTP_USERNAME = os.getenv("EMAIL_NOTIFICATIONS_SMTP_USERNAME", "")
EMAIL_NOTIFICATIONS_SMTP_PASSWORD = os.getenv("EMAIL_NOTIFICATIONS_SMTP_PASSWORD", "")
EMAIL_NOTIFICATIONS_FROM_ADDRESS = os.getenv("EMAIL_NOTIFICATIONS_FROM_ADDRESS", "notification@photopoint.com")

# SMS notification settings
SMS_NOTIFICATIONS_ENABLED = os.getenv("SMS_NOTIFICATIONS_ENABLED", "True") != "False"
SMS_NOTIFICATIONS_SERVICE_URL = os.getenv("SMS_NOTIFICATIONS_SERVICE_URL", "")
SMS_NOTIFICATIONS_API_KEY = os.getenv("SMS_NOTIFICATIONS_API_KEY", "")

# Push notification settings
PUSH_NOTIFICATIONS_ENABLED = os.getenv("PUSH_NOTIFICATIONS_ENABLED", "True") != "False"
PUSH_NOTIFICATIONS_SERVICE_URL = os.getenv("PUSH_NOTIFICATIONS_SERVICE_URL", "")
PUSH_NOTIFICATIONS_API_KEY = os.getenv("PUSH_NOTIFICATIONS_API_KEY", "")

# Telegram notification settings
TELEGRAM_NOTIFICATIONS_ENABLED = os.getenv("TELEGRAM_NOTIFICATIONS_ENABLED", "True") != "False"
TELEGRAM_NOTIFICATIONS_BOT_TOKEN = os.getenv("TELEGRAM_NOTIFICATIONS_BOT_TOKEN", "")
